### ISSUE TITLE
Any way to accept a group invite ?

### ISSUE THREAD

**Issue by NiTRoeSE** [signal-golang/textsecure#43]
Hi i use "signal-web-gateway" wich uses textsecure to send signal messages from check_mk.
This works fine to a single contact.

We want to send to a group which basically seems to be possible.
The problem is that i found no way to accept the group invitation with textsecure.

Is there any way or workaround to achieve this ?

Thanks in advanced!

**Comment by nanu-c** [comment]
There is a workaround, 
* delete the invitation
* set a name in the config
* send a message from textsecure to the person that's going to invite the bot to the group or wait 1day in order to get the profilekey updated
* when you can see the set name in the profile it's save to invite the gateway again.

**Comment by NiTRoeSE** [comment]
> There is a workaround,
> 
> * delete the invitation
> * set a name in the config
> * send a message from textsecure to the person that's going to invite the bot to the group or wait 1day in order to get the profilekey updated
> * when you can see the set name in the profile it's save to invite the gateway again.

Thanks for your answer, i give it a try. :)
In the meanwhile i was able to link a signal-desktop instance to textsecure to accept the invitation. But i always get a error and nothing happens.

* set a name in the config --> you mean the config.yml ? .. if so a name was already present.

```yaml

tel: "+49364188997744"
uuid: 15fffa87-2db9-4c85-8d70-9f543453453ae6
server: https://textsecure-service.whispersystems.org:443
rootCA: ""
proxy: ""
verificationType: voice
storageDir: .storage
unencryptedStorage: false
storagePassword: password!
loglevel: ""
userAgent: ""
alwaysTrustPeerID: false
accountCapabilities:
  uuid: false
  gv2: true
  storage: false
  gv1-migration: false
discoverableByPhoneNumber: false
profileKey:
- 82
- 253
- 252
- 7
- 33
- 130
- 101
- 79
- 22
- 63
- 95
- 15
- 154
- 98
- 29
- 114
- 149
- 102
- 199
- 77
- 16
- 3
- 124
- 77
- 123
- 187
- 4
- 7
- 209
- 226
- 198
- 73
name: Monitoring 


```

* when you can see the set name in the profile it's save to invite the gateway again

   Wich profile did you mean ? The profile from the bot in my signal app on my phone?

Thanks again ;)
